namespace AvantiPoint.Aspire.Hosting.Cloudflare.Publishing.Generators;

/// <summary>
/// Generates a minimal Dockerfile that runs a published .NET app on the ASP.NET runtime image.
/// The image targets linux/amd64 (required by Cloudflare Containers). The published output is
/// expected under an <c>app/</c> folder next to the Dockerfile (the build context).
/// </summary>
internal static class DockerfileGenerator
{
    public static string Generate(string assemblyName, int port)
        => $"""
            # Generated by AvantiPoint.Aspire.Hosting.Cloudflare. Cloudflare Containers require linux/amd64.
            FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
            WORKDIR /app
            COPY app/ ./
            ENV ASPNETCORE_URLS=http://+:{port}
            EXPOSE {port}
            ENTRYPOINT ["dotnet", "{assemblyName}.dll"]

            """;
}
