using System.Text.Json;

namespace AvantiPoint.Aspire.Hosting.Cloudflare.Publishing.Generators;

/// <summary>
/// Generates the Worker entrypoint that fronts the container: a Durable Object class extending the
/// Cloudflare <c>Container</c> helper, plus a fetch handler that forwards requests to a container instance.
/// The resolved application environment variables are passed to the container via the <c>envVars</c> property.
/// </summary>
internal static class WorkerShimGenerator
{
    private static readonly JsonSerializerOptions s_envOptions = new() { WriteIndented = true };

    public static string GenerateWorker(string className, string bindingName, int port, string sleepAfter, IReadOnlyDictionary<string, string> environment)
        => $$"""
            // Generated by AvantiPoint.Aspire.Hosting.Cloudflare.
            import { Container, getContainer } from "@cloudflare/containers";

            export class {{className}} extends Container {
              defaultPort = {{port}};
              sleepAfter = "{{sleepAfter}}";
              envVars = {{SerializeEnvironment(environment)}};
            }

            export default {
              async fetch(request, env) {
                return getContainer(env.{{bindingName}}).fetch(request);
              },
            };

            """;

    private static string SerializeEnvironment(IReadOnlyDictionary<string, string> environment)
        => environment.Count == 0
            ? "{}"
            : JsonSerializer.Serialize(environment, s_envOptions);

    public static string GeneratePackageJson(string workerName)
        => $$"""
            {
              "name": "{{workerName}}",
              "private": true,
              "type": "module",
              "dependencies": {
                "@cloudflare/containers": "^0.3.7"
              }
            }

            """;
}
