namespace AvantiPoint.Aspire.Hosting.Cloudflare.Publishing.Generators;

/// <summary>
/// Generates the Worker entrypoint that fronts the container: a Durable Object class extending the
/// Cloudflare <c>Container</c> helper, plus a fetch handler that forwards requests to a container instance.
/// </summary>
internal static class WorkerShimGenerator
{
    public static string GenerateWorker(string className, string bindingName, int port, string sleepAfter)
        => $$"""
            // Generated by AvantiPoint.Aspire.Hosting.Cloudflare.
            import { Container, getContainer } from "@cloudflare/containers";

            export class {{className}} extends Container {
              defaultPort = {{port}};
              sleepAfter = "{{sleepAfter}}";
            }

            export default {
              async fetch(request, env) {
                return getContainer(env.{{bindingName}}).fetch(request);
              },
            };

            """;

    public static string GeneratePackageJson(string workerName)
        => $$"""
            {
              "name": "{{workerName}}",
              "private": true,
              "type": "module",
              "dependencies": {
                "@cloudflare/containers": "^0.3.7"
              }
            }

            """;
}
