<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AvantiPoint.Aspire.Hosting.Cloudflare.R2/AvantiPoint.Aspire.Hosting.Cloudflare.R2.csproj" />
    <ProjectReference Include="../../src/AvantiPoint.Aspire.Cloudflare.R2/AvantiPoint.Aspire.Cloudflare.R2.csproj" />
  </ItemGroup>

</Project>
