<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Aspire.Hosting.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AvantiPoint.Aspire.Hosting.Cloudflare.AI/AvantiPoint.Aspire.Hosting.Cloudflare.AI.csproj" />
    <ProjectReference Include="../../src/AvantiPoint.Aspire.Cloudflare.AI/AvantiPoint.Aspire.Cloudflare.AI.csproj" />
  </ItemGroup>

</Project>
